### ISSUE TITLE
Problem with optins text - not saving

### ISSUE THREAD

**Issue by erscampbell** [postmatic/postmatic-basic#10]
Submitted on behalf of Andy:

> I have changed the text in my pop up opt in box but the changes are not reflecting on my site. I have hit save changes. Can you help me sort this out?

_Note:_ He's using the bottom slider optin.

**Comment by Vernal** [comment]
Can you reproduce @erscampbell ?

**Comment by erscampbell** [comment]
@Vernal I'll give it a try and let you know what I find.

**Comment by erscampbell** [comment]
@Vernal Unable to reproduce - in several tests, all of my changes saved correctly.

**Comment by Vernal** [comment]
Great. Thanks for checking on it.


On June 23, 2016 at 1:35:32 PM, Elissa Campbell (notifications@github.com)
wrote:

@Vernal <https://github.com/Vernal> Unable to reproduce - in several tests,
all of my changes saved correctly.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/postmatic/postmatic-basic/issues/10#issuecomment-228124102>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAE8JEmBZPIyra0CucwIU4MQJrT9RDfqks5qOsPagaJpZM4IwW56>
.
