### ISSUE TITLE
Remove unwanted promotional tabs

### ISSUE THREAD

**Issue by cyberhobo** [postmatic/postmatic-basic#36]

**Comment by cyberhobo** [comment]
@Vernal shall i remove the notes and analytics promo tabs?

**Comment by cyberhobo** [comment]
I went ahead and removed them, couldn't imagine why we'd keep them.

**Comment by Vernal** [comment]
Yes please.


On October 21, 2016 at 5:08:13 PM, Dylan Kuhn (notifications@github.com)
wrote:

@Vernal <https://github.com/Vernal> shall i remove the notes and analytics
promo tabs?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/postmatic/postmatic-basic/issues/36#issuecomment-255465585>,
or mute the thread
